name: Bundle Install

on: [push, pull_request]

jobs:
  bundle_install_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' 

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Commit and push Gemfile.lock
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add Gemfile.lock
        git commit -m 'Add Gemfile.lock'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
